version: '3.8'

services:
  backend:
    build:
      context: ./anarchy-copilot
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./anarchy_copilot.db:/app/anarchy_copilot.db
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./anarchy-copilot/frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8000
