services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - ~/.nuclei:/root/.nuclei
      - dev-cache:/root/.cache
    network_mode: "host" # Allow direct access from browser
    environment:
      - PYTHONPATH=/app:/app/anarchy-copilot
      - PYTEST_ADDOPTS="-v --import-mode=append"
      - NUCLEI_TEMPLATES=/root/.nuclei/templates
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DISABLE_HTTPS=0
      # API Settings
      - ANARCHY_API_TITLE=Anarchy Copilot API
      - ANARCHY_API_VERSION=0.1.0
      - ANARCHY_DEBUG=true
      - ANARCHY_CORS_ORIGINS=http://localhost:3000
      # Proxy Settings
      - ANARCHY_PROXY_HOST=0.0.0.0
      - ANARCHY_PROXY_PORT=8081
      - ANARCHY_PROXY_INTERCEPT_REQUESTS=true
      - ANARCHY_PROXY_INTERCEPT_RESPONSES=true
      - ANARCHY_PROXY_MAX_CONNECTIONS=100
      - ANARCHY_PROXY_MAX_KEEPALIVE_CONNECTIONS=20
      - ANARCHY_PROXY_KEEPALIVE_TIMEOUT=30
    env_file:
      - .env
    command: [ "/usr/local/bin/dev-entrypoint.sh", "start" ]
    healthcheck:
      test: [ "CMD", "/usr/local/bin/healthcheck.sh" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 30s

  proxy:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - ./certs:/app/certs
      - proxy-data:/app/data
    environment:
      - PYTHONPATH=/app:/app/anarchy-copilot
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      # API Settings
      - ANARCHY_API_TITLE=Anarchy Copilot API
      - ANARCHY_API_VERSION=0.1.0
      - ANARCHY_DEBUG=true
      - ANARCHY_CORS_ORIGINS=http://localhost:3000
      # Proxy Settings
      - ANARCHY_PROXY_HOST=0.0.0.0
      - ANARCHY_PROXY_PORT=8081
      - ANARCHY_PROXY_INTERCEPT_REQUESTS=true
      - ANARCHY_PROXY_INTERCEPT_RESPONSES=true
      - ANARCHY_PROXY_MAX_CONNECTIONS=100
      - ANARCHY_PROXY_MAX_KEEPALIVE_CONNECTIONS=20
      - ANARCHY_PROXY_KEEPALIVE_TIMEOUT=30
      # Certificate Settings
      - CA_CERT_PATH=/app/certs/ca.crt
      - CA_KEY_PATH=/app/certs/ca.key
    network_mode: "host" # Allow direct external connections for proxy traffic
    dns:
      - 8.8.8.8 # Use Google's DNS
      - 1.1.1.1 # Use Cloudflare's DNS as backup
    command: >
      python -m debugpy --listen 0.0.0.0:5679 -m uvicorn proxy.server.asgi:app  --host 0.0.0.0  --port 8080  --reload  --reload-delay 2  --log-level debug  --proxy-headers  --timeout-keep-alive 75  --forwarded-allow-ips '*'  --lifespan on  --use-colors  --loop asyncio
    ports:
      - "8080:8080"
      - "8081:8081"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules
    network_mode: "host" # Allow direct browser access
    environment:
      - NODE_ENV=development
      - REACT_APP_API_BASE_URL=http://localhost:8000
      - REACT_APP_PROXY_URL=http://localhost:8081
      - PORT=3000 # Set explicit port for React dev server
      - WDS_SOCKET_PORT=3000
    depends_on:
      dev:
        condition: service_healthy
      proxy:
        condition: service_started
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:3000" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  anarchy:
    driver: bridge

volumes:
  dev-cache:
    name: anarchy-copilot_dev-cache
  proxy-certs:
    name: anarchy-copilot_proxy-certs
  proxy-data:
    name: anarchy-copilot_proxy-data
  frontend-node-modules:
    name: anarchy-copilot_frontend-node-modules
