services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - type: bind
        source: .
        target: /app
      - type: bind
        source: ~/.nuclei
        target: /root/.nuclei
      - type: volume
        source: dev-cache
        target: /root/.cache
      - type: bind
        source: ./certs
        target: /app/certs
    ports:
      - "8000:8000" # API port
    environment:
      - PYTHONPATH=/app:/app/anarchy-copilot
      - PYTEST_ADDOPTS="-v --import-mode=append"
      - NUCLEI_TEMPLATES=/root/.nuclei/templates
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DISABLE_HTTPS=0
      # API Settings
      - ANARCHY_API_TITLE=Anarchy Copilot API
      - ANARCHY_API_VERSION=0.1.0
      - ANARCHY_DEBUG=true
      - ANARCHY_CORS_ORIGINS=http://localhost:3000,ws://localhost:3000,http://localhost:8000,ws://localhost:8000
      # Proxy Settings (only for client configuration)
      - ANARCHY_PROXY_HOST=proxy
      - ANARCHY_PROXY_PORT=8083
    env_file:
      - .env
    entrypoint: [ "/usr/local/bin/api-entrypoint.sh" ]
    command: [ "start" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/health" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 30s

  proxy:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: [ "/usr/local/bin/proxy-entrypoint.sh" ]
    command: [ "start" ]
    volumes:
      - .:/app
      - dev-cache:/root/.cache
      - type: bind
        source: ./certs
        target: /app/certs
      - type: bind
        source: ./data
        target: /app/data
    ports:
      - "8083:8083" # Proxy port
      - "5678:5678" # Debug port
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - DEBUG=1
      - CA_CERT_PATH=/app/certs/ca.crt
      - CA_KEY_PATH=/app/certs/ca.key
      # Database settings
      - SQLALCHEMY_DATABASE_URL=sqlite+aiosqlite:///./data/proxy.db
      # Proxy Settings
      - ANARCHY_PROXY_HOST=0.0.0.0
      - ANARCHY_PROXY_PORT=8083
      - ANARCHY_PROXY_INTERCEPT_REQUESTS=true
      - ANARCHY_PROXY_INTERCEPT_RESPONSES=true
      - ANARCHY_PROXY_MAX_CONNECTIONS=100
      - ANARCHY_PROXY_MAX_KEEPALIVE_CONNECTIONS=20
      - ANARCHY_PROXY_KEEPALIVE_TIMEOUT=30
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://dev:8000/api/proxy/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    volumes:
      - type: bind
        source: ./frontend
        target: /app
      - type: volume
        source: frontend-node-modules
        target: /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_BASE_URL=http://localhost:8000
      - REACT_APP_PROXY_URL=http://localhost:8083
      - REACT_APP_WS_URL=ws://localhost:8000/api/proxy/ws
      - PORT=3000 # Set explicit port for React dev server
      - WDS_SOCKET_PORT=3000
    depends_on:
      dev:
        condition: service_healthy
      proxy:
        condition: service_started
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  dev-cache:
    name: anarchy-copilot_dev-cache
  proxy-data:
    name: anarchy-copilot_proxy-data
  frontend-node-modules:
    name: anarchy-copilot_frontend-node-modules
