[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.mypy]
mypy_path = "stubs"
ignore_missing_imports = true
namespace_packages = true
explicit_package_bases = true
