from typing import Any, Callable, List, Optional, Sequence, Type, Union

class BaseRoute:
    def matches(self, scope: dict) -> tuple[bool, dict]: ...
    async def handle(self, scope: dict, receive: Callable, send: Callable) -> None: ...
