"""Type stubs for BeautifulSoup."""
from typing import Optional, Any, Iterator, Mapping

class PageElement:
    text: str
    name: str
    attrs: Mapping[str, Any]
    string: Optional[str]

class Tag(PageElement):
    title: Optional["Tag"]
    def __init__(self) -> None: ...
    def find(self, name: Optional[str] = None, attrs: Optional[dict[str, Any]] = None, recursive: bool = True, text: Optional[str] = None, **kwargs: Any) -> Optional["Tag"]: ...
    def find_next(self, name: Optional[str] = None, attrs: Optional[dict[str, Any]] = None, text: Optional[str] = None, **kwargs: Any) -> Optional["Tag"]: ...
    def find_all(self, name: Optional[str] = None, attrs: Optional[dict[str, Any]] = None, recursive: bool = True, text: Optional[str] = None, limit: Optional[int] = None, **kwargs: Any) -> list["Tag"]: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def __getitem__(self, key: str) -> str: ...

class BeautifulSoup(Tag):
    title: Optional[Tag]
    def __init__(self, markup: str = "", features: str = "html.parser", **kwargs: Any) -> None: ...
