from typing import Any, Dict, Optional, Union

class Engine:
    def connect(self) -> 'Connection': ...
    def dispose(self) -> None: ...
    
class Connection:
    def close(self) -> None: ...
    def execute(self, *args: Any, **kwargs: Any) -> 'Result': ...
    def begin(self) -> 'Transaction': ...

class Transaction:
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    
class Result:
    def fetchall(self) -> list: ...
    def fetchone(self) -> Optional[tuple]: ...
    def scalar(self) -> Any: ...
