name: Type Check

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - '**.pyi'
      - 'requirements*.txt'
      - 'mypy.ini'
      - '.github/workflows/type-check.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'
      - '**.pyi'
      - 'requirements*.txt'
      - 'mypy.ini'
      - '.github/workflows/type-check.yml'

jobs:
  typecheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-typing.txt

    - name: Cache mypy
      uses: actions/cache@v3
      with:
        path: .mypy_cache
        key: mypy-${{ matrix.python-version }}-${{ hashFiles('**/*.py') }}
        restore-keys: |
          mypy-${{ matrix.python-version }}-

    - name: Run type checks
      run: |
        python scripts/check_types.py --strict

    - name: Generate type check report
      if: always()
      run: |
        python scripts/check_types.py --report

    - name: Upload type check report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: type-check-report-py${{ matrix.python-version }}
        path: type_report/
        retention-days: 14

    - name: Check stub files
      run: |
        python -m flake8 **/*.pyi

    - name: Verify type completeness
      if: matrix.python-version == '3.10'
      run: |
        python -m pytype proxy/

  notify:
    needs: typecheck
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Check status
      if: contains(needs.typecheck.result, 'failure')
      run: |
        echo "Type checking failed!"
        exit 1
